package com.cg.Hibernate;

import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.Transaction;
import org.hibernate.cfg.Configuration;

/**
 * Hello world!
 *
 */
public class App 
{
    public static void main( String[] args )
    {
       Student s=new Student();
       s.setFirstName("Panja");
       s.setLastName("Vinod");
       
       Configuration con=new Configuration().configure("hibernate.cfg.xml").addAnnotatedClass(Student.class);
       SessionFactory sessionFactory = con.buildSessionFactory();
       Session session = sessionFactory.openSession();
       try {
    	   Transaction transaction = session.beginTransaction();
   
    	   session.save(s);
    	 
    	   int studentIdToRetrieve = s.getId(); // Use the ID generated by Hibernate
           Student retrievedStudent = session.get(Student.class, studentIdToRetrieve);

           if (retrievedStudent != null) {
               System.out.println("Retrieved Student Data:");
               System.out.println("ID: " + retrievedStudent.getId());
               System.out.println("First Name: " + retrievedStudent.getFirstName());
               System.out.println("Last Name: " + retrievedStudent.getLastName());
           } else {
               System.out.println("Student with ID " + studentIdToRetrieve + " not found.");
           }
    	   transaction.commit();
       }finally{
    	   session.close();
    	   sessionFactory.close();
       }
       
    }
}
